"""Update room model

Revision ID: 76c558262ef5
Revises: dbda550156ce
Create Date: 2024-01-14 20:34:39.290605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '76c558262ef5'
down_revision: Union[str, None] = 'dbda550156ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('room_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'message', 'room', ['room_id'], ['id'])
    op.drop_column('message', 'receiver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('receiver_id', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'room_id')
    # ### end Alembic commands ###
